name: Delete runners

on:
  schedule:
    - cron: '12 * * * *' # every hour at 12 minutes past
  workflow_dispatch:

jobs:
  delete-offline-runners:
    name: 'Delete offline runners'
    runs-on: elvia-runner
    steps:
      - name: Get GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Delete offline runners
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const org = process.env.GITHUB_REPOSITORY.split('/')[0];
            if (!org) {
              throw new Error(`Could not determine org: ${org}`);
            }

            const runners = await github.rest.actions.listSelfHostedRunnersForOrg({
              org,
            });

            for (const { id: runner_id, status, name, busy } of runners.data.runners) {
              if (status === 'offline' && name.startsWith('elvia-runner-') && !busy) {
                console.log(
                  `Runner with id ${runner_id} and name ${name} has status ${status} and is not busy. Deleting...`,
                );
                await github.rest.actions.deleteSelfHostedRunnerFromOrg({
                  org,
                  runner_id,
                });
              }
            }
