name: Generate image

# TODO: add cron trigger
on:
  push:
    branches: [master, develop]
    paths-ignore: ['README.md', '.github/renovate.json']

env:
  IMAGE_TEMPLATE: './images/ubuntu/templates/ubuntu-22.04.pkr.hcl'

jobs:
  generate-packer-image:
    name: 'Generate Packer image'
    runs-on: ubuntu-latest # We don't use Elvia runner to avoid race conditions
    environment: ${{ github.head_ref == 'master' || github.ref_name == 'master' && 'prod' || 'dev' }}
    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3

    - name: Set environment variables
      run: |
        echo "IMAGE_NAME=github-runner-$(date +%s)" >> "$GITHUB_ENV"
        echo "TEMP_RESOURCE_GROUP_NAME=packer-build-delete-me-$RANDOM$RANDOM" >> "$GITHUB_ENV"

    - name: Build image and publish to Azure
      run: |
        packer init "$IMAGE_TEMPLATE"
        packer build \
          -var 'managed_image_name=${{ env.IMAGE_NAME }}' \
          -var 'temp_resource_group_name=${{ env.TEMP_RESOURCE_GROUP_NAME }}' \
          "$IMAGE_TEMPLATE"
      env:
        ARM_SUBSCRIPTION_ID: ${{ vars.ARM_SUBSCRIPTION_ID }}
        ARM_CLIENT_ID: ${{ vars.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_RESOURCE_GROUP: ${{ vars.ARM_RESOURCE_GROUP }}
        ARM_RESOURCE_LOCATION: ${{ vars.ARM_RESOURCE_LOCATION }}

    - name: Login to Azure CLI
      if: ${{ !cancelled() }}
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ vars.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ vars.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ vars.ARM_TENANT_ID }}"}'

    - name: Clean up resources created by Packer if build fails
      if: failure()
      run: |
        az group delete \
          --name '${{ env.TEMP_RESOURCE_GROUP_NAME }}' \
          --force-deletion-types Microsoft.Compute/virtualMachines \
          --yes

    - name: Update VMSS with new image and delete old image
      run: |
        image_id=$(az image show -g '${{ vars.ARM_RESOURCE_GROUP }}' -n '${{ env.IMAGE_NAME }}' --query id -o tsv)
        old_image_id=$(az vmss show -g '${{ vars.ARM_RESOURCE_GROUP }}' -n '${{ vars.VMSS_NAME }}' --query virtualMachineProfile.storageProfile.imageReference.id -o tsv)
        az vmss update \
          --output none \
          --resource-group '${{ vars.ARM_RESOURCE_GROUP }}' \
          --name '${{ vars.VMSS_NAME }}' \
          --set virtualMachineProfile.storageProfile.imageReference.id="$image_id"
        sleep 10
        az image delete \
          --output none \
          --ids "$old_image_id"
