name: Sync upstream

on:
  schedule:
    - cron: '54 3 * * 0' # every Sunday at 03:54
  workflow_dispatch:

jobs:
  sync-upstream:
    name: 'Sync upstream'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      BASE_BRANCH: 'trunk'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      - name: Run update script
        run: go run main.go
        env:
          ACCEPT_ALL: 'true'

      - name: Get GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Check for any changes and make a pull request
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes to commit.'
            exit 0
          fi

          git config user.email '${{ vars.GH_APP_USER_EMAIL }}'
          git config user.name '${{ vars.GH_APP_USERNAME }}'

          branch_name="chore/update-image-$(date +%s)"
          git checkout -b "$branch_name"
          git add .
          git commit -m 'Update image'
          git push -u origin "$branch_name"

          gh pr create \
            -r '3lvia/core-developer' \
            -B '${{ env.BASE_BRANCH }}' \
            -f
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
