name: Sync upstream

on:
  schedule:
    - cron: '54 3 * * 0' # every Sunday at 03:54
  workflow_dispatch:

jobs:
  sync-upstream:
    name: 'Sync upstream'
    runs-on: elvia-runner
    permissions:
      contents: write
    env:
      BASE_BRANCH: 'trunk'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      - name: Run update script
        run: go run main.go
        env:
          ACCEPT_ALL: 'true'

      - name: Get GitHub App token for repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Commit changes and set branch name
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes to commit.'
            exit 0
          fi

          branch_name="chore/update-image-$(date +%s)"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

          git config user.email '${{ vars.GH_APP_USER_EMAIL }}'
          git config user.name '${{ vars.GH_APP_USERNAME }}'

          git checkout -b "$branch_name"
          git add .
          git commit -m 'Update image'
          git push -u origin "$branch_name"

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;

            const { data: pullRequest } = await github.rest.pulls.create({
              owner,
              repo,
              title: 'Update image',
              head: '${{ env.BRANCH_NAME }}',
              base: 'trunk',
            })

            console.log(`Created pull request: ${pullRequest.html_url}`)
