name: Sync upstream

on:
  schedule:
    - cron: '54 3 * * 0' # every Sunday at 03:54
  workflow_dispatch:

jobs:
  sync-upstream:
    name: 'Sync upstream'
    runs-on: elvia-runner
    permissions:
      contents: write
    env:
      BASE_BRANCH: 'trunk'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BASE_BRANCH }}

      - name: Setup Go
        uses: actions/setup-go@v5

      - name: Setup Packer
        uses: hashicorp/setup-packer@v3

      - name: Run update script
        run: go run main.go
        env:
          ACCEPT_ALL: 'true'

      - name: Get GitHub App token for repository
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      - name: Commit changes and set branch name
        run: |
          if [[ -z "$(git status --porcelain)" ]]; then
            echo 'No changes to commit.'
            exit 0
          fi

          branch_name="chore/update-image-$(date +%s)"
          echo "BRANCH_NAME=$branch_name" >> $GITHUB_ENV

          git config user.email '${{ vars.GH_APP_USER_EMAIL }}'
          git config user.name '${{ vars.GH_APP_USERNAME }}'

          git checkout -b "$branch_name"
          git add .
          git commit -m 'Update image'
          git push -u origin "$branch_name"

      - name: Create pull request
        uses: actions/github-script@v7
        with:
          github-token: ${{ steps.app-token.outputs.token }}
          script: |
            const { owner, repo } = context.repo;

            const body = `# ⬆️ Image update

            This pull request updates the Packer configuration to the latest tag from [runner-images](https://github.com/actions/runner-images).

            ## ❓ What To Do

            **1.** Confirm that the '**Generate image**' workflow has passed; if not you can try to re-run it.
            **2.** Review the changes in the Packer configuration file and check that they look sensible. Any changes to Markdown files can be ignored.
            **3.** Go [here](https://github.com/3lvia/core-github-actions-templates/actions/workflows/test-actions.yml), click on '_Run workflow_' and select \`elvia-runner-dev\` as the runner. This will run the '**Test actions**' workflow using the new image.
            **4.** Once the '**Test actions**' workflow has passed, you can merge this pull request.
            **5.** After merging, the '**Generate image**' workflow will run again and create a new image. You should confirm that this workflow passes too.

            Optionally, you can also run another '**Test actions**' workflow using \`elvia-runner\` after merging to confirm that the new image works as expected.
            `;

            const team_reviewers = ['core-developer'];

            const { data: pullRequest } = await github.rest.pulls.create({
              owner,
              repo,
              title: 'Update image',
              head: '${{ env.BRANCH_NAME }}',
              base: 'trunk',
              body,
            })

            console.log(`Created pull request: ${pullRequest.html_url}`)

            await github.rest.pulls.requestReviewers({
              owner,
              repo,
              pull_number: pullRequest.number,
              team_reviewers,
            });

            console.log(`Requested review from teams: ${team_reviewers.join(', ')}`)
