name: Test update script

on:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

jobs:
  test-update-script:
    name: 'Test update script'
    runs-on: elvia-runner
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Setup Packer
      uses: hashicorp/setup-packer@v3

    - name: Run update script apply
      run: |
        go run main.go --apply
        if [[ -n "$(git status --porcelain)" ]]; then
          echo '## :warning: Changes detected' >> "$GITHUB_STEP_SUMMARY"
          echo 'Please run `go run main.go --apply` and commit the changes.' >> "$GITHUB_STEP_SUMMARY"
          exit 1
        fi
      env:
        ACCEPT_ALL: 'true'

    - name: Get GitHub App token for repository
      if: failure()
      uses: actions/create-github-app-token@v1
      id: app-token
      with:
        app-id: ${{ vars.GH_APP_ID }}
        private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

    - name: Post GitHub comment
      if: failure()
      uses: actions/github-script@v7
      with:
        github-token: ${{ steps.app-token.outputs.token }}
        script: |
          const body = `## :warning: Changes detected
          Please run \`go run main.go --apply\` and commit the changes.
          `;

          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body,
          });

    - name: Run update script
      run: go run main.go
      env:
        ACCEPT_ALL: 'true'
